rewrite non-conan build instructions
nemtech/catapult-server pull request #112
Opened 2020-11-16 14:58 UTC by Jaguar0625

conan is preferred approach. 

for non-preferred approach provide instructions for linux / os x that are more closely aligned with what official builds do for easier maintenance.

2020-11-16 15:16 UTC, segfaultxavi requested changes
Found only one oversight. I haven't checked the correctness of the instructions.

2020-11-16 15:16 UTC, segfaultxavi commented on docs/BUILD-manual.md
> +Assume an environment variable named `CAT_DEPS_DIR` is defined as the directory that should contain all catapult directories.
```suggestion
Assume an environment variable named `CAT_DEPS_DIR` is defined as the directory that should contain all catapult dependencies.
```

I assume you meant this?

2020-11-17 12:40 UTC, Jaguar0625 commented
@segfaultxavi - any more comments?

2020-11-17 13:19 UTC, segfaultxavi commented
No comments regarding the text, but I haven't verified the instructions are correct.

2020-11-17 13:21 UTC, Jaguar0625 commented
Can you please verify? I'd like to wrap this up today.

2020-11-17 18:10 UTC, Jaguar0625 commented
Needed to merge before updating dependencies. 

@segfaultxavi - please open issue if there are issues with scripts/instructions.

2020-11-17 18:10 UTC, closed without merging