automation of manual tasks
nemtech/catapult-server pull request #163
Opened 2021-02-24 12:45 UTC by mm-s

This patch provides automation for the steps described at  'docs/RUNNETWORKLIN.md' and `docs/RUNPEERLIN.md`.

New commands:
  bootstrapping a local network with one nemesis node: `scripts/configure-manual minnet create`
  adding a node: `scripts/configure-manual minnet node new <port>`
  deleting a node: `scripts/configure-manual minnet node rm <port>`
  deleting the network: `scripts/configure-manual minnet clean`

2021-02-24 16:45 UTC, mm-s commented
I can reproduce the error reported by travis:
`pushd scripts; pylint --rcfile .pylintrc --load-plugins pylint_quotes --output-format=parseable ./*/*.py`

The error is not caused by this branch because I can reproduce the same error on branch main. :/

2021-02-26 08:27 UTC, segfaultxavi requested changes
I have made a couple of obvious comments, but my main problem is understanding the **purpose** of this patch.
You add a set of commands but their description is very short.
What does it mean "automates all previous steps"? Can I just replace the **whole** RUNNETWORKLIN guide with `scripts/configure-manual.sh minnet create`?
So `minnet create` creates the nemesis block?
And then I can run `minnet node new` many times and create several peer nodes that will run concurrently?
What does `minnet` mean?

I would like to see a lot more details explained (for example the folder names used), along with the general purpose of these new commands.

(Somebody else should review the code accuracy).

2021-02-26 08:27 UTC, segfaultxavi commented on scripts/configure-manual.sh
> +	    info <port>    Displays information about the node at specified port.
Careful, you're mixing TABS and SPACES and the alignment is broken.

2021-02-26 08:27 UTC, segfaultxavi commented on scripts/configure-manual.sh
> +#./cert-generate.sh
Do you want to commit commented-out code?

2021-02-26 08:27 UTC, segfaultxavi commented on docs/RUNPEERLIN.md
> +The command `scripts/configure-manual.sh minnet node` automates all previous steps.
`minnet node` is not a command, right? I would need to use `minnet node new`.

2021-02-26 11:52 UTC, mm-s commented on scripts/configure-manual.sh
> +	    info <port>    Displays information about the node at specified port.
fixed

2021-02-26 11:52 UTC, mm-s commented on scripts/configure-manual.sh
> +#./cert-generate.sh
coverted to a reference. fixed.

2021-02-26 12:37 UTC, mm-s commented on docs/RUNPEERLIN.md
> +The command `scripts/configure-manual.sh minnet node` automates all previous steps.
@segfaultxavi I've added moref contextual explanation in the docs.
also changed the name minnet to devnet.

2021-02-26 12:47 UTC, mm-s commented on docs/RUNPEERLIN.md
> +The command `scripts/configure-manual.sh minnet node` automates all previous steps.
The purpose of this patch.
This tool for devs, rather than more system users (I call them with the oldish name sysops) who would choose symbol-bootstrap instead.
The benefit of using this workflow is a straight sources->build->deploy_locally->run journey, without using docker container.
Mostly is a tool I wrote for automating my own tasks.

2021-03-01 09:56 UTC, segfaultxavi requested changes
Now that I understand that this is a development tool I don't have further comments (besides making it extra clear that this is a development tool).

2021-03-01 09:56 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +## Fast lane: devnet
```suggestion
## Fast lane (Development only)
```

2021-03-01 09:56 UTC, segfaultxavi commented on docs/RUNPEERLIN.md
> +## Fast lane: devnet
```suggestion
## Fast lane (Development only)
```

2021-03-01 09:56 UTC, segfaultxavi commented on docs/RUNPEERLIN.md
> +Log are written in directory ../node_<port>/logs
```suggestion
Logs are written in directory ../node_<port>/logs
```

2021-03-01 10:05 UTC, mm-s commented on docs/RUNPEERLIN.md
> +Log are written in directory ../node_<port>/logs
github defect: The comment is for
 making vertical space in
  the container <div> so I can
   access the button at the bottom
    of the popup accepting
     the commit 
     suggestion

2021-03-01 10:23 UTC, mm-s commented
Regarding checks that are failing. details show the cause is
"pylint --rcfile .pylintrc --load-plugins pylint_quotes --output-format=parseable ./*/*.py"

but I do the following sequence:

```
git clone https://github.com/nemtech/catapult-server.git
 cd catapult-server/scripts/
 pylint --rcfile .pylintrc --load-plugins pylint_quotes --output-format=parseable ./*/*.py
 echo $?
16
```
So it also fails in `main` branch.
I dont know if it local to me or why the main branch checks succeed in github

2021-03-01 12:13 UTC, Jaguar0625 commented
> this is a development tool

I don't think this is the right audience. This should be usable (and supported) for users that do not want to or cannot use bootstrap. If it's just for "developers", I don't see the value in it. The instructions that it is based on are intended for sys ops people.

2021-03-03 11:39 UTC, mm-s commented
> > this is a development tool
> 
> I don't think this is the right audience. This should be usable (and supported) for users that do not want to or cannot use bootstrap. If it's just for "developers", I don't see the value in it. The instructions that it is based on are intended for sys ops people.

It provides an alternative path from sources to running catapult network in local machine.
I value it as a developer savin me the time to recreate a new network manually.

this is a tool I made for me and shared in the hope it could be found useful.

2021-03-23 13:27 UTC, gimer requested changes

2021-03-23 13:27 UTC, gimer commented on docs/BUILD-manual.md
> +export LD_LIBRARY_PATH=$CAT_DEPS_DIR/boost/lib:$CAT_DEPS_DIR/facebook/lib:$CAT_DEPS_DIR/google/lib:$CAT_DEPS_DIR/mongodb/lib:$CAT_DEPS_DIR/zeromq/lib:./
what is `.` at the end? (what requires it?)

2021-03-23 13:27 UTC, gimer commented on scripts/configure-manual.sh
> +certificate = ca.cert.pem
please rename to ca.crt.pem (just to user `crt` in all 'filename' places)

2021-03-23 13:27 UTC, gimer commented on scripts/configure-manual.sh
> +			tlspk=`openssl pkey -pubin -in ca.pubkey.pem -noout -text | openssl dgst -sha256 -hex | awk '{ print $NF }'` || { echo "Error tls pubkey" && exit 1; }
does this script passes `shellcheck`? (haven't checked and don't see here https://travis-ci.com/github/nemtech/catapult-server/builds)


right now command is `shellcheck --format=gcc ./*/*.sh `

2021-03-23 13:27 UTC, gimer commented on scripts/configure-manual.sh
> +#ls -la ../resources/private-test.properties
needed?

2021-03-23 14:57 UTC, Jaguar0625 requested changes

2021-03-23 14:57 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +a 1 liner command for creating pre-configured networks suitable for development purposes.
1 liner => one liner

2021-03-23 14:57 UTC, Jaguar0625 commented on docs/RUNPEERLIN.md
> +a 1 liner command for creating pre-configured networks suitable for development purposes.
1 liner => one liner

2021-03-23 14:57 UTC, Jaguar0625 commented on docs/RUNPEERLIN.md
> +`devnet` is a local private network that runs in the host computer via its local IP address.
in => on ?

2021-03-23 14:57 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +The command `scripts/configure-manual.sh devnet create` automates all previous steps providing
not sure if i'd use the term "devnet" or "onebox"

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
>  #!/bin/bash
please don't mix spaces and tabs

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +debs="git gcc g++ cmake curl libssl-dev ninja-build pkg-config libpython-dev"
delete - duplicate?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +#procedure cert generation. based on: https://raw.githubusercontent.com/tech-bureau/catapult-service-bootstrap/master/common/ruby/script/cert-generate.sh --output cert-generate.sh
please don't link to tech-bureau repos

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +		#ca.cnf
comment needed?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +		#node.cnf
comment needed?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +CN = peer-node-1-account
can you vary CN per node?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +CN = peer-node-1
can you vary?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +			cxxflags="-O3 -rdynamic"
why do you need to set custom flags? shouldn't `CMAKE_BUILD_TYPE` be enough?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +		local lfriendlyName=`cat resources/config-node.properties | grep "^friendlyName =" | sed "s/friendlyName = *\(.*\)/\1/"`
comments needed?

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +function devnet_update_known_peers_item {
this is mostly the same as previous function

2021-03-23 14:57 UTC, Jaguar0625 commented on scripts/configure-manual.sh
> +		[[ $? -ne 0 ]] && echo "Please install symbol-bootstrap. npm -g install symbol-bootstrap" && exit 1
why is there a symbol-bootstrap dependency?

2021-04-01 20:20 UTC, mm-s commented
Closed to inactivity. Will propose again if the functions are needed.

2021-04-01 20:20 UTC, closed without merging