Note on backing up the voting key
nemtech/catapult-server pull request #169
Opened 2021-03-19 11:54 UTC by segfaultxavi

2021-03-19 15:39 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +
I think this would be more readable if moved after the line running the votingkey tool?

Also, maybe simpler to write something like: do not backup any file produced by the votingkey tool (e.g. private_key_tree1.dat). 

Also, in the second sentence, I think it should be "it is" not "they are" since it's referring to the single file.

2021-03-19 15:39 UTC, Jaguar0625 requested changes
Please consider rephrasing.

2021-03-23 13:02 UTC, gimer approved these changes

2021-03-23 14:23 UTC, Jaguar0625 approved these changes

2021-03-23 14:29 UTC, Jaguar0625 commented
Merged as e86a94b96,

2021-03-23 14:29 UTC, closed without merging