Add gcc version in docs/BUILD-conan.md
nemtech/catapult-server pull request #92
Opened 2020-09-30 13:26 UTC by segfaultxavi

It's specified like this in BUILDLIN.md but it's missing in BUILD-conan.md

2020-09-30 14:58 UTC, Jaguar0625 commented on docs/BUILD-conan.md
> + * gcc 9.2
please include recommended versions for all supported compilers (gcc, clang, msvc)

2020-09-30 14:58 UTC, Jaguar0625 commented on docs/BUILD-conan.md
> + * gcc 9.2
conan supports all three

[ofc, only one is needed]

2020-09-30 15:41 UTC, Jaguar0625 requested changes
Please make it clearer that conan works with multiple supported compilers, not just gcc.

2020-10-05 16:08 UTC, Jaguar0625 approved these changes

2020-10-05 16:31 UTC, gimer approved these changes

2020-10-06 14:16 UTC, Jaguar0625 commented
Merged as 0125a1065.

2020-10-06 14:16 UTC, closed without merging