Add section about Voting to RUNNETWORKLIN.md
nemtech/catapult-server pull request #94
Opened 2020-10-05 08:27 UTC by segfaultxavi

I am not certain at all that I got this right. Please check carefully.

Also, format and links have been fixed both in RUNNETWORK and RUNPEER docs.

Fixes #73

2020-10-05 16:14 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +    ```sh
is there a reason you added a lot of indents? 

would prefer if you made such changes separately so that this one is focused on new text for voting keys.

2020-10-05 17:07 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +    ```sh
I used actual markdown lists (by unescaping de dots on the list numbers) so the indents are required to keep things at the proper depth. I think it reads more easily now. 

I agree having this in the same PR is bad manners, but they are in separate commits so the git history will be clean.
Still, I can create a separate PR if you want.

2020-10-05 19:12 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +    ```sh
would prefer separate because we squash/merge PRs.

2020-10-06 07:43 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +    ```sh
Done!

2020-10-06 14:40 UTC, Jaguar0625 commented
@segfaultxavi - can you please rebase this on main?

2020-10-06 15:47 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
This is kind of a contradiction since nemesis is inherently finalized.

2020-10-06 15:49 UTC, Jaguar0625 requested changes

2020-10-06 15:49 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Each node of the network can host zero or more voting accounts. In order to be an eligible voter an account must:
zero or one

2020-10-06 15:49 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +   * Replace ``<VOTER_PRIVATE_KEY>`` with the private key of an account that has received sufficient voting mosaics.
has received -> { owns, contains, possesses }

voting -> harvesting

2020-10-06 15:52 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
i'd probably remove whole sentence.

2020-10-06 16:02 UTC, dgarcia360 requested changes

2020-10-06 16:02 UTC, dgarcia360 commented on docs/RUNNETWORKLIN.md
> +1. Own at least ``minVoterBalance`` mosaics defined in ``config-network.properties``.
Might be good to add "harvesting mosaics" to differentiate them from the network currency.

2020-10-06 19:06 UTC, dgarcia360 requested changes

2020-10-06 19:06 UTC, dgarcia360 commented on docs/RUNNETWORKLIN.md
> +    ./catapult.tools.linker --resources ../ --type voting --secret <VOTER_PRIVATE_KEY> --linkedPublicKey <VOTING_PUBLIC_KEY> --output ../txes/tx0.bin
@Jaguar0625 Is the output file name chosen conflicting with https://github.com/nemtech/catapult-server/pull/94/files#diff-e15bf14647a852b685148ac56c3d75b1R143? Shall voting transactions need to be stored in a separate file (e.g ``tx1.bin``)?

2020-10-07 08:26 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
This first sentence just summarizes how finalization works, to put the concept of voting in perspective. It does not talk about the nemesis block so I do not see the contradiction. Can you elaborate?

2020-10-07 08:34 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +1. Own at least ``minVoterBalance`` mosaics defined in ``config-network.properties``.
Done

2020-10-07 08:34 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +   * Replace ``<VOTER_PRIVATE_KEY>`` with the private key of an account that has received sufficient voting mosaics.
Done

2020-10-07 08:34 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +Each node of the network can host zero or more voting accounts. In order to be an eligible voter an account must:
Done

2020-10-07 08:35 UTC, segfaultxavi commented
I've implemented some of the comments. I'm waiting on the answers for the open questions.

2020-10-07 11:39 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
section title is 

> Append the Voting Keys to the nemesis block

but then you're discussing voting key transactions after nemesis, so it seemed a bit incongruous to me.

2020-10-07 11:41 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +    ./catapult.tools.linker --resources ../ --type voting --secret <VOTER_PRIVATE_KEY> --linkedPublicKey <VOTING_PUBLIC_KEY> --output ../txes/tx0.bin
yes, that's a good suggestion to change name here.
alternatively you could prefix files with vrf_ voting_

2020-10-07 16:40 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +    ./catapult.tools.linker --resources ../ --type voting --secret <VOTER_PRIVATE_KEY> --linkedPublicKey <VOTING_PUBLIC_KEY> --output ../txes/tx0.bin
Done

2020-10-07 16:42 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
I followed what was in the VRF key section, which also talks about appending to the nemesis block. Should I change both section titles?
Is "Registering the VRF/Voting Keys" a better title?

2020-10-08 16:04 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
i think current title with appending is more accurate, so i would leave it.

2020-10-08 16:08 UTC, Jaguar0625 requested changes

2020-10-08 16:08 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +1. Own a certain amount of harvesting mosaics defined in ``config-network.properties`` between ``minHarvesterBalance`` and ``maxHarvesterBalance``. See [Configuring network properties](https://docs.s
is it possible to have See ... on a new line?

2020-10-08 16:08 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
>     * Replace ``<HARVESTER_PRIVATE_KEY>`` with the private key of an account that has received sufficient harvesting mosaics in ``resources/mijin-test.properties`` ``[distribution>cat:harvest]``.
would change this to "owns" to match below

2020-10-08 16:08 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
appending is fine. `Before transactions are permanently added...` sentence doesn't seem to correspond to anything in VRF section. i don't really see it's value since this md is just explaining how to prepare a nemesis block.

2020-10-08 16:08 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +1. Own at least ``minVoterBalance`` harvesting mosaics (``harvestingMosaicId``) defined in ``config-network.properties``. See [Configuring network properties](https://docs.symbolplatform.com/guides/n
either mention `harvestingMosaicId` in VRF section or remove it here for consistency

2020-10-09 08:23 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
OK, removed. How does it look now?

2020-10-09 08:23 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +1. Own a certain amount of harvesting mosaics defined in ``config-network.properties`` between ``minHarvesterBalance`` and ``maxHarvesterBalance``. See [Configuring network properties](https://docs.s
Sure thing!

2020-10-09 08:23 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
>     * Replace ``<HARVESTER_PRIVATE_KEY>`` with the private key of an account that has received sufficient harvesting mosaics in ``resources/mijin-test.properties`` ``[distribution>cat:harvest]``.
Done

2020-10-09 08:24 UTC, segfaultxavi commented on docs/RUNNETWORKLIN.md
> +1. Own at least ``minVoterBalance`` harvesting mosaics (``harvestingMosaicId``) defined in ``config-network.properties``. See [Configuring network properties](https://docs.symbolplatform.com/guides/n
Yeah, rephrased the VRF section a bit.

2020-10-09 11:44 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +   * Replace ``<VOTING_PUBLIC_KEY>`` with the public key obtained from ``catapult.tools.votingkey``.
@gimer - do these settings exist?

2020-10-09 11:52 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +Before transactions are permanently added to the blockchain the blocks need to be [finalized](https://docs.symbolplatform.com/concepts/block.html#finalization), a processing involving several nodes i
:+1:

2020-10-09 14:27 UTC, Jaguar0625 commented on docs/RUNNETWORKLIN.md
> +   * Replace ``<VOTING_PUBLIC_KEY>`` with the public key obtained from ``catapult.tools.votingkey``.
ok - i misread it. it’s fine and will merge.

2020-10-09 14:28 UTC, Jaguar0625 approved these changes

2020-10-09 14:32 UTC, closed without merging